version: '3.8'

services:
  api:
    container_name: api
    build: .
    restart: on-failure
    ports:
      - ${PORT:-3001}:${PORT:-3001}
    env_file: .env
    networks:
      - primary
    depends_on:
      - postgres

  postgres:
    container_name: psql
    image: postgres:16.1-alpine
    restart: on-failure
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-onechat}
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    networks:
      - primary


volumes:
  db:
networks:
  primary: