version: '3.8'

services:
  prometheus:
    container_name: prom-server
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prom:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitor

  # Metrics for linux hosts for windows support use `windows_exporter`
  node_exporter:
    container_name: linux-metrics
    image: prom/node-exporter
    restart: unless-stopped
    ports:
      - 9100:9100
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - monitor

  grafana-loki:
    container_name: loki
    image: grafana/loki
    restart: unless-stopped
    ports:
      - 3100:3100
    depends_on:
      - grafana
    volumes:
      - loki:/loki
    networks:
      - monitor

volumes:
  prom:
  loki:
  grafana:
networks:
  monitor:
