name: Build Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['20']
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: 'yarn'
      - name: Building Backend 
        run: |
          yarn install --ignore-optional --frozen-lockfile
          yarn build
